name = "Renice Cubed"
author = "Wechirok"
version = "2.0.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7e55a1adb303b7e8f9a3addc40e6f195ee140f6458c67fa657b082db6aabefc"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
