name = "Renice Cubed"
author = "Wechirok"
version = "1.1.4-release"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f65fdf7811d054144e20c9307023dcf4b3cba0fee9982c55096312ba32079740"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
